### ISSUE TITLE
Integer divide by zero error

### ISSUE THREAD

**Issue by Weilin37** [markus-wa/cs-demo-minifier#29] opened 2020-05-16 15:43 UTC
Hello,

I tried to copy your code from the readme on minifying a demo to json. The demo file is a GOTV downloaded here: https://www.hltv.org/matches/2341150/astralis-vs-faze-esl-one-road-to-rio-europe

I put the path to my .dem file and got this error:

"2020/05/16 11:38:53 runtime error: integer divide by zero"

This error appears if I try the cmd line tool as well. I am using the latest version of Golang (1.14.2)

Here is the entire stack trace:

```2020/05/16 11:38:53 runtime error: integer divide by zero
stacktrace:
goroutine 19 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        C:/Go/src/runtime/debug/stack.go:24 +0xa4
github.com/markus-wa/demoinfocs-golang/pkg/demoinfocs.NewParserWithConfig.func1(0x879980, 0xc0002ee3d0)
        C:/Users/Weilin/go/src/github.com/markus-wa/demoinfocs-golang/pkg/demoinfocs/parser.go:309 +0x36
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1(0xc0001b4000)
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:190 +0x6e
panic(0x879980, 0xc0002ee3d0)
        C:/Go/src/runtime/panic.go:969 +0x174
github.com/markus-wa/godispatch.callConsumerCode.func1()
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:120 +0x8f
panic(0x879980, 0xc0002ee3c0)
        C:/Go/src/runtime/panic.go:969 +0x174
github.com/markus-wa/godispatch.callConsumerCode.func1()
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:120 +0x8f
panic(0x856e20, 0xca7a20)
        C:/Go/src/runtime/panic.go:969 +0x174
github.com/markus-wa/cs-demo-minifier.(*minifier).frameDone(0xc0001a4090)
        C:/Users/Weilin/go/src/github.com/markus-wa/cs-demo-minifier/csminify.go:128 +0x31f
reflect.Value.call(0x835880, 0xc0000886c0, 0x13, 0x8d23bc, 0x4, 0xc00005bae0, 0x1, 0x1, 0xc0001b7440, 0x0, ...)
        C:/Go/src/reflect/value.go:460 +0x8b2
reflect.Value.Call(0x835880, 0xc0000886c0, 0x13, 0xc00005bae0, 0x1, 0x1, 0xc0002e6188, 0xed6d0994a2512a01, 0xed00000008010101)
        C:/Go/src/reflect/value.go:321 +0xbb
github.com/markus-wa/godispatch.callConsumerCode(0x835880, 0xc0000886c0, 0x13, 0xc00005bae0, 0x1, 0x1)
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:123 +0x93
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0001b4060, 0x856700, 0xcdee10)
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:109 +0x24a
github.com/markus-wa/demoinfocs-golang/pkg/demoinfocs.(*parser).handleFrameParsed(0xc000084300, 0xcdee10)
        C:/Users/Weilin/go/src/github.com/markus-wa/demoinfocs-golang/pkg/demoinfocs/parsing.go:372 +0xab
reflect.Value.call(0x835240, 0xc000088690, 0x13, 0x8d23bc, 0x4, 0xc00005bf28, 0x1, 0x1, 0xc0001b6360, 0x0, ...)
        C:/Go/src/reflect/value.go:460 +0x8b2
reflect.Value.Call(0x835240, 0xc000088690, 0x13, 0xc00005bf28, 0x1, 0x1, 0xc0002e6048, 0xc0a7f55a07474501, 0xc000000008010104)
        C:/Go/src/reflect/value.go:321 +0xbb
github.com/markus-wa/godispatch.callConsumerCode(0x835240, 0xc000088690, 0x13, 0xc00005bf28, 0x1, 0x1)
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:123 +0x93
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0001b4000, 0x823b60, 0xcdee10)
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:109 +0x24a
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0001b4000, 0x823b60, 0xcdee10)
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:195 +0x69
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0001b4000, 0xc0001b40c0)
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:171 +0xfb
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues
        C:/Users/Weilin/go/src/github.com/markus-wa/godispatch/dispatch.go:157 +0x15f
```

**Comment by markus-wa** [comment] 2020-05-16 20:51
Hi @Weilin37 

Unfortunately the header of this demo is corrupt:

`{Filestamp:HL2DEMO Protocol:4 NetworkProtocol:13752 ServerName:ESL Match Server #1 ClientName:GOTV Demo MapName:de_dust2 GameDirectory:csgo PlaybackTime:0s PlaybackTicks:0 PlaybackFrames:0 SignonLength:0}`

note the `PlaybackFrames:0` and `PlaybackTime:0s`.

because of this the library is not able to identify how frequently it should take snapshots.

I'm not sure if this is completely fixable or not but we should certainly give a better error message than this.

**Comment by Weilin37** [comment] 2020-05-16 21:11
Hi @markus-wa , I tried another GOTV demo that I saved back in January. It worked then, presumably with an older version of the code (don't know which one), but now it also gives the same error message.  It seems like a systematic problem. Was there anything changed since January??

**Comment by markus-wa** [comment] 2020-05-16 21:45
this one works: https://gitlab.com/markus-wa/cs-demos/-/blob/master/default.7z

but there have been some changes since jan, notably the upgrade to demoinfocs-golang v2.0.0.

I checked with v0.2.9 and it seems like it used to "work" sort of. it created a minified json but the snapshots were broken, only game events were correctly recorded. (instead of panic due to division by 0, `SnapshotRate` resulted in `NAN` / `-9223372036854775808`)

**Comment by Weilin37** [comment] 2020-05-17 13:47
Gotcha, I'll try the demo you provided. Hmm, I wonder why the GOTV demos had a corrupt header.

**Comment by markus-wa** [comment] 2020-05-17 14:02
I _think_ this happens if demo recording is interrupted abruptly instead of safely via `stop` command.

But I'm not 100℅ sure

**Comment by LarsKoelpin** [comment] 2020-06-04 06:29
Hey @markus-wa  i ran into the same issue when I was kicked from faceit because of match end and could not properly stop the demo. So I can confirm it happens when the demo is not stopped properly.

Is there any way to patch the demo header via Hex-Editor of something similar? (Set Playback tick size to last tick or smoething?)

**Comment by markus-wa** [comment] 2020-06-04 08:38
Should be possible:

The first 1112 bits are other stuff, then a 32 bit float for playback time and a 32 bit float for playback ticks:
https://github.com/markus-wa/demoinfocs-golang/blob/master/pkg/demoinfocs/parsing.go#L54

But I'm not sure about the encoding, you might have to reverse engineer that from the link above and markus-wa/gobitread

I think the real fix will be to get the tickrate after the serverinfo message has come in, which will give us the tick interval: https://github.com/markus-wa/demoinfocs-golang/blob/master/pkg/demoinfocs/net_messages.go#L68

**Comment by Weilin37** [comment] 2020-06-20 18:24
@markus-wa 

Great that it seems we found a solution. Is the bug fixed yet?

**Comment by markus-wa** [comment] 2020-06-27 12:25
fixed and released in v0.4.3: https://github.com/markus-wa/cs-demo-minifier/releases/tag/v0.4.3

**Comment by markus-wa** [comment] 2020-06-27 12:25
sorry it took so long @Weilin37 :sweat_smile:

**Closed by markus-wa** 2020-06-27 12:25 UTC
Labels: bug

**Comment by Weilin37** [comment] 2020-06-27 15:39
no worries @markus-wa , thanks so much!
